from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal, NoReturn, Protocol, TypeGuard

if TYPE_CHECKING:
    from collections.abc import Callable


class Context(Protocol):
    working_dir: str
    metadata: dict[str, Any]
    environ: dict[str, str]

    def register(self, fn: Callable[[Exception], None]) -> None: ...
    def is_cancelled(self) -> bool: ...
    def get_error(self) -> Exception | None: ...
    def raise_if_cancelled(self): ...
    def wait(self, timeout: float | None) -> Exception | None: ...


class CancelledContext(Context, Protocol):
    def is_cancelled(self) -> Literal[True]: ...
    def get_error(self) -> Exception: ...
    def raise_if_cancelled(self) -> NoReturn: ...
    def wait(self, timeout: float | None) -> Exception: ...


def is_context_cancelled(ctx: Context) -> TypeGuard[CancelledContext]:
    return ctx.is_cancelled()
